version: '3.8'

services:
  ai-detection:
    build: .
    container_name: ai-face-detection
    ports:
      - "3000:80"
    restart: unless-stopped
    volumes:
      # Logs persistentes
      - nginx-logs:/var/log/nginx
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - ai-detection-network

networks:
  ai-detection-network:
    driver: bridge

volumes:
  nginx-logs:
    driver: local