version: '3.8'

services:
  alert-face-web:
    build: .
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.alert-face-web.rule=Host(`alert-face.seu-dominio.com`)"
      - "traefik.http.routers.alert-face-web.tls=true"
      - "traefik.http.routers.alert-face-web.tls.certresolver=letsencrypt"
    networks:
      - web

networks:
  web:
    external: true